---
# file: roles/iscsiinitiator/tasks/main.yml
- name: packages install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-initiator-utils

- name: iscsid start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - iscsid

- name: initiatorname.iscsi setting
  template:
    src: initiatorname.iscsi.j2
    dest: /etc/iscsi/initiatorname.iscsi
    owner: root
    group: root
    mode: 0644
  register: initiatorname_results

- name: iscsid restart
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - iscsid
  when: initiatorname_results.changed

- name: check iscsiadm node
  command: "/usr/sbin/iscsiadm -m node"
  register: iscsiadm
  changed_when: false
  failed_when: false

- name: discovery iscsiadm node
  command: "/usr/sbin/iscsiadm -m discovery -t st -p {{ hostvars[item].ansible_default_ipv4.address }}"
  with_items: "{{ groups.target }}"
  when: iscsiadm.rc != 0

- name: restart iscsi
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - iscsi
  when: iscsiadm.rc != 0
