---
# file: roles/iscsiinitiator/tasks/main.yml
- name: packages install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-initiator-utils

- name: iscsid start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - iscsid
    - iscsi
