---
# file: roles/iscsitarget/tasks/iscsi_target.yml
- block:
  - name: check backstores block of target
    command: "/bin/targetcli ls /backstores/block/{{ item.block_name }}"
    register: targetcli
    changed_when: false
    failed_when: false
    with_items: "{{ disk_item.partition }}"

  - name: create backstores block of target
    command : >-
      /bin/targetcli /backstores/block create name={{ item.item.block_name }} dev={{ disk_item.disk }}{{ item.item.num}}
    with_items: "{{ targetcli.results }}"
    when: item.rc != 0



  when: >
    disk_item.disk is defined and
    disk_item.disk != ""

