---
# file: roles/iscsitarget/tasks/main.yml
- name: packages install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - targetcli

- name: setup iscsi partition
  include_tasks: iscsi_partition.yml
  with_items: "{{ iscsi_disk }}"
  loop_control:
    loop_var: disk_item

- name: target start
  service:
    name: target
    state: started
    enabled: yes
