---
# file: roles/iscsitarget/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - scsi-target-utils

- name: external disk status
  stat: path=/dev/{{external_disk}}
  register: external_disk_status

- name: external disk check
  fail: msg="can not find external disk."
  when: external_disk_status.stat.exists == false

- name: external disk format status
  stat: path=/dev/"{{external_disk}}"1
  register: external_disk_format

- name: mklabel
  shell: parted -s /dev/{{external_disk}} mklabel gpt
  when: external_disk_format.stat.exists == false

- name: sfex partition
  shell: parted -s /dev/{{external_disk}} mkpart SFEX 0G 1G
  when: external_disk_format.stat.exists == false

- name: pgdata partition
  shell: parted -s /dev/{{external_disk}} mkpart DATA 1G 100G
  when: external_disk_format.stat.exists == false

- name: pgxlog partition
  shell: parted -s /dev/{{external_disk}} mkpart WAL 100G 110G
  when: external_disk_format.stat.exists == false

- name: pgarch partition
  shell: parted -s /dev/{{external_disk}} mkpart ARC 110G 120G
  when: external_disk_format.stat.exists == false

- name: nfs partition
  shell: parted -s /dev/{{external_disk}} mkpart NFS 120G 200G
  when: external_disk_format.stat.exists == false

